PLAP-503 Add OpenAPI 3 documentation for oneapp-verivox-adapter.
Placons/redoc pull request #3
Opened 2021-04-14 12:02 UTC by cmanios

2021-04-14 12:57 UTC, nstergiou-prodyna requested changes

2021-04-14 12:57 UTC, nstergiou-prodyna commented on openapi-docs/oneapp-verivox-adapter.yaml
> +servers:
Let's not add server urls.
This service in particular is not publicly available

2021-04-15 07:12 UTC, cmanios commented on openapi-docs/oneapp-verivox-adapter.yaml
> +servers:
Hi @nstergiou-prodyna !

This service is at the moment only publicly available in DEV and STG environment at the moment according to the [Ingress controller](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/) deployment configuration in `_deployment` directory.

I removed the production environment in ef4a6d577bacf2015add45a874cb7ef75718bcf1 as discussed offline.

Thanks!

2021-04-15 07:22 UTC, nstergiou-prodyna approved these changes

2021-04-15 07:27 UTC, merged