PLAP-503 Added openapi3 docs for email-verification-service
Placons/redoc pull request #4
Opened 2021-04-14 12:16 UTC by nstergiou-prodyna

2021-04-14 12:23 UTC, cmanios requested changes

2021-04-14 12:23 UTC, cmanios commented on openapi-docs/oneapp-email-verification-service.yaml
> +- url: /
Hi @nstergiou-prodyna !

Please add the server urls for our APIs:

```yaml
servers:
  - url: https://services.dev.lionaire.app/oneapp-email-verification-service
    description: Placons Development environment
  - url: https://services.stg.lionaire.app/oneapp-email-verification-service
    description: Placons Staging environment
  - url: https://services.prd.lionaire.app/oneapp-email-verification-service
```
Thanks!

2021-04-14 12:23 UTC, cmanios commented on openapi-docs/oneapp-email-verification-service.yaml
> +                $ref: '#/components/schemas/app.VerificationEmail'
Hi @nstergiou-prodyna !

Please remove the `app` prefix which was added automatically by `swag` using the go package:

```diff
-$ref: '#/components/schemas/app.VerificationEmail'
+$ref: '#/components/schemas/VerificationEmail'

Thanks!

2021-04-14 12:23 UTC, cmanios commented on openapi-docs/oneapp-email-verification-service.yaml
> +              $ref: '#/components/schemas/ports.EmailVerificationCodeRequest'
Hi @nstergiou-prodyna !

Please remove the `ports.` prefix which was added automatically by `swag` using the go package:

```diff
-$ref: '#/components/schemas/ports.EmailVerificationCodeRequest'
+$ref: '#/components/schemas/EmailVerificationCodeRequest'

Thanks!

2021-04-14 12:23 UTC, cmanios commented on openapi-docs/oneapp-email-verification-service.yaml
> +              $ref: '#/components/schemas/ports.EmailVerificationRequest'
Hi @nstergiou-prodyna !

Please remove the `ports.` prefix which was added automatically by `swag` using the go package:

```diff
-$ref: '#/components/schemas/ports.EmailVerificationRequest'
+$ref: '#/components/schemas/EmailVerificationRequest'

Thanks!

2021-04-14 12:23 UTC, cmanios commented on openapi-docs/oneapp-email-verification-service.yaml
> +    app.VerificationEmail:
Hi @nstergiou-prodyna !

Please remove the `app` prefix which was added automatically by `swag` using the go package:

```diff
-app.VerificationEmail:
+VerificationEmail:

Thanks!

2021-04-14 12:23 UTC, cmanios commented on openapi-docs/oneapp-email-verification-service.yaml
> +    ports.EmailVerificationCodeRequest:
Hi @nstergiou-prodyna !

Please remove the `ports.` prefix which was added automatically by `swag` using the go package:

```diff
-ports.EmailVerificationCodeRequest:
+EmailVerificationCodeRequest:
```
Thanks!

2021-04-14 12:23 UTC, cmanios commented on openapi-docs/oneapp-email-verification-service.yaml
> +    ports.EmailVerificationRequest:
Hi @nstergiou-prodyna !

Please remove the `ports.` prefix which was added automatically by `swag` using the go package:

```diff
-ports.EmailVerificationRequest:
+EmailVerificationRequest:
```

Thanks!

2021-04-14 12:28 UTC, nstergiou-prodyna commented on openapi-docs/oneapp-email-verification-service.yaml
> +- url: /
I wouldn't want to add anything extra, let's keep this as an "as-is migration" task.
Some of the services are not publicly available anyway

2021-04-14 12:53 UTC, nstergiou-prodyna commented on openapi-docs/oneapp-email-verification-service.yaml
> +                $ref: '#/components/schemas/app.VerificationEmail'
Done

2021-04-14 12:53 UTC, nstergiou-prodyna commented on openapi-docs/oneapp-email-verification-service.yaml
> +              $ref: '#/components/schemas/ports.EmailVerificationCodeRequest'
Done

2021-04-14 12:53 UTC, nstergiou-prodyna commented on openapi-docs/oneapp-email-verification-service.yaml
> +    app.VerificationEmail:
Done

2021-04-14 12:53 UTC, nstergiou-prodyna commented on openapi-docs/oneapp-email-verification-service.yaml
> +    ports.EmailVerificationCodeRequest:
Done

2021-04-14 12:53 UTC, nstergiou-prodyna commented on openapi-docs/oneapp-email-verification-service.yaml
> +    ports.EmailVerificationRequest:
Done

2021-04-14 12:53 UTC, nstergiou-prodyna commented on openapi-docs/oneapp-email-verification-service.yaml
> +              $ref: '#/components/schemas/ports.EmailVerificationRequest'
Done

2021-04-15 06:54 UTC, nstergiou-prodyna commented on openapi-docs/oneapp-email-verification-service.yaml
> +- url: /
Added dev, stg urls as agreed

2021-04-15 07:00 UTC, cmanios approved these changes

2021-04-15 07:18 UTC, merged